/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.StudentGradeDAO;
import Model.Student;
import Helper.FrameDragListener;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.EventQueue;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dev-StOrM
 */
public class GradeManagementForm extends javax.swing.JFrame {

    private boolean editModeState;
    private ArrayList<Student> list;
    private int currentIndex = -1;

    /**
     * Creates new form ScoresManagement
     *
     * @param username
     */
    public GradeManagementForm(String username) {
        initComponents();
        initTable();

        resetForm();
        fillToTable();

        lblUserName.setText(username);

        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }

    private void initTable() {
        DefaultTableModel tblModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        String columns[] = {"Mã SV", "Họ tên", "Tiếng Anh", "Tin học", "GDTC", "Điểm TB"};
        tblModel.setColumnIdentifiers(columns);

        tblStudents.setModel(tblModel);
        tblStudents.setSelectionMode(0);
        if (tblStudents.getColumnModel().getColumnCount() > 0) {
            tblStudents.getColumnModel().getColumn(0).setMaxWidth(60);
            tblStudents.getColumnModel().getColumn(1).setMinWidth(120);
            tblStudents.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblStudents.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblStudents.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblStudents.getColumnModel().getColumn(5).setPreferredWidth(80);
        }
    }

    private void fillToTable() {
        list = StudentGradeDAO.getAll();

        // order list by DTB - descending
        Comparator<Student> comp = (Student o1, Student o2) -> {
            if (o1.getDTB() == o2.getDTB()) {
                return 0;
            } else if (o1.getDTB() < o2.getDTB()) {
                return 1;
            } else {
                return -1;
            }
        };
        Collections.sort(list, comp);

        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0);

        for (Student x : list) {
            Object[] row = {x.getMaSV(), x.getHoTen(), x.getTiengAnh(), x.getTinHoc(),
                x.getGDTC(), x.getDTB()};
            model.addRow(row);
        }
        tblStudents.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainContainer = new javax.swing.JPanel();
        lblFormTitle = new javax.swing.JLabel();
        FormIcon = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        Banner = new javax.swing.JPanel();
        fploy = new javax.swing.JLabel();
        pnlLogOut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtMaSVTim = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblDiemTB = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTiengAnh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTinHoc = new javax.swing.JTextField();
        txtGiaoDucTC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblMaSV = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlNew = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlSave = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlDelete = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlEditMode = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblEditState = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblPrevious = new javax.swing.JLabel();
        lblLast = new javax.swing.JLabel();
        lblFirst = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        lblAuthor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm sinh viên");
        setUndecorated(true);

        MainContainer.setBackground(java.awt.Color.white);
        MainContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        MainContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFormTitle.setText("Quản lý điểm sinh viên");
        MainContainer.add(lblFormTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 190, 30));

        FormIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fpt_icon_1.png"))); // NOI18N
        MainContainer.add(FormIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 30));

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_minimize_window_24px_1.png"))); // NOI18N
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        MainContainer.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 30, 30));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_close_window_24px.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        MainContainer.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 30, 30));

        Banner.setBackground(new java.awt.Color(242, 111, 33));
        Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fploy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banner_crop.png"))); // NOI18N
        Banner.add(fploy, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, -1, 60));

        pnlLogOut.setBackground(new java.awt.Color(242, 111, 33));
        pnlLogOut.setToolTipText("Đăng xuất");
        pnlLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNewMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Log-Out-icon.png"))); // NOI18N
        pnlLogOut.add(jLabel1);

        Banner.add(pnlLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 60, 60));

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserName.setText("Username");
        lblUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Banner.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 150, 40));

        MainContainer.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 830, 60));

        jPanel1.setBackground(new java.awt.Color(248, 224, 219));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(242, 113, 37))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaSVTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaSVTim.setText("SV007");
        jPanel1.add(txtMaSVTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 32, 300, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Mã SV");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 31, -1, 30));

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-32px.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.setIconTextGap(20);
        btnSearch.setInheritsPopupMenu(true);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 24, 144, 45));

        MainContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 620, 90));

        jPanel3.setBackground(new java.awt.Color(248, 224, 219));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 119, 26)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Họ tên SV");

        lblDiemTB.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblDiemTB.setForeground(new java.awt.Color(0, 102, 178));
        lblDiemTB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiemTB.setText("8");
        lblDiemTB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Điểm TB");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mã SV");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tiếng Anh");

        txtTiengAnh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTiengAnh.setText("8");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tin học");

        txtTinHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTinHoc.setText("8");

        txtGiaoDucTC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGiaoDucTC.setText("8");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Giáo dục TC");

        lblHoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(0, 102, 178));
        lblHoTen.setText("Nguyen Trong Tai");

        lblMaSV.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaSV.setForeground(new java.awt.Color(0, 102, 178));
        lblMaSV.setText("PS15069");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaoDucTC, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lblDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtTiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtGiaoDucTC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MainContainer.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 620, 240));

        tblStudents.setBackground(new java.awt.Color(248, 224, 219));
        tblStudents.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblStudents.setForeground(new java.awt.Color(51, 51, 51));
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"SV001", "Nguyen Van Teo", "10", "8", "9", "9"}
            },
            new String [] {
                "Mã SV", "Họ Tên", "Tiếng Anh", "Tin học", "GDTC", "Điểm TB"
            }
        ));
        tblStudents.setFocusable(false);
        tblStudents.setShowGrid(false);
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);
        if (tblStudents.getColumnModel().getColumnCount() > 0) {
            tblStudents.getColumnModel().getColumn(1).setMinWidth(120);
        }

        MainContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 830, 180));

        jPanel4.setBackground(new java.awt.Color(242, 111, 33));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setFocusable(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(13, 176, 75));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, -1));

        pnlNew.setBackground(new java.awt.Color(242, 111, 33));
        pnlNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNewMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-32px.png"))); // NOI18N

        jLabel16.setDisplayedMnemonic('N');
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("New");

        jSeparator2.setForeground(new java.awt.Color(13, 176, 75));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout pnlNewLayout = new javax.swing.GroupLayout(pnlNew);
        pnlNew.setLayout(pnlNewLayout);
        pnlNewLayout.setHorizontalGroup(
            pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNewLayout.setVerticalGroup(
            pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlNewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );

        jPanel4.add(pnlNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 50));

        pnlSave.setBackground(new java.awt.Color(242, 111, 33));
        pnlSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNewMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save-32px.png"))); // NOI18N

        jLabel11.setDisplayedMnemonic('S');
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Save");

        javax.swing.GroupLayout pnlSaveLayout = new javax.swing.GroupLayout(pnlSave);
        pnlSave.setLayout(pnlSaveLayout);
        pnlSaveLayout.setHorizontalGroup(
            pnlSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaveLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSaveLayout.setVerticalGroup(
            pnlSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSaveLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(pnlSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 50));

        pnlDelete.setBackground(new java.awt.Color(242, 111, 33));
        pnlDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNewMouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete-32px.png"))); // NOI18N

        jLabel13.setDisplayedMnemonic('D');
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Delete");

        javax.swing.GroupLayout pnlDeleteLayout = new javax.swing.GroupLayout(pnlDelete);
        pnlDelete.setLayout(pnlDeleteLayout);
        pnlDeleteLayout.setHorizontalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlDeleteLayout.setVerticalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(pnlDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));

        pnlEditMode.setBackground(new java.awt.Color(242, 111, 33));
        pnlEditMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEditMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEditModeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNewMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update-32px.png"))); // NOI18N

        lblEditState.setDisplayedMnemonic('U');
        lblEditState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEditState.setForeground(new java.awt.Color(255, 255, 255));
        lblEditState.setText("Edit: ");

        javax.swing.GroupLayout pnlEditModeLayout = new javax.swing.GroupLayout(pnlEditMode);
        pnlEditMode.setLayout(pnlEditModeLayout);
        pnlEditModeLayout.setHorizontalGroup(
            pnlEditModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditModeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblEditState, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlEditModeLayout.setVerticalGroup(
            pnlEditModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditModeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditModeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addComponent(lblEditState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(pnlEditMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 50));

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/next-32px.png"))); // NOI18N
        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });
        jPanel4.add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        lblPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/previous-32px.png"))); // NOI18N
        lblPrevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPreviousMouseClicked(evt);
            }
        });
        jPanel4.add(lblPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        lblLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/last-32px.png"))); // NOI18N
        lblLast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLastMouseClicked(evt);
            }
        });
        jPanel4.add(lblLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        lblFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/first-32px.png"))); // NOI18N
        lblFirst.setToolTipText("");
        lblFirst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFirstMouseClicked(evt);
            }
        });
        jPanel4.add(lblFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(13, 176, 75));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, -1));

        jSeparator5.setForeground(new java.awt.Color(13, 176, 75));
        jSeparator5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jSeparator5.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, -1));

        MainContainer.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 350));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 2);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        lblAuthor.setForeground(new java.awt.Color(0, 102, 204));
        lblAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthor.setText("© Copyright - Nguyễn Trọng Tài - PS15069");
        lblAuthor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAuthorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAuthorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAuthorMouseExited(evt);
            }
        });
        jPanel2.add(lblAuthor);

        MainContainer.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 830, 20));

        getContentPane().add(MainContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        int confirmation = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?",
                "Thoát chương trình", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        setState(GradeManagementForm.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void pnlNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNewMouseEntered
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(255, 137, 91));
    }//GEN-LAST:event_pnlNewMouseEntered

    private void pnlNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNewMouseExited
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(242, 111, 33));
    }//GEN-LAST:event_pnlNewMouseExited

    private void lblFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFirstMouseClicked
        currentIndex = 0;
        showDetail();
    }//GEN-LAST:event_lblFirstMouseClicked

    private void lblPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPreviousMouseClicked
        currentIndex--;
        if (currentIndex < 0) {
            currentIndex = list.size() - 1;
        }
        showDetail();
    }//GEN-LAST:event_lblPreviousMouseClicked

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        currentIndex++;
        if (currentIndex >= list.size()) {
            currentIndex = 0;
        }
        showDetail();
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLastMouseClicked
        currentIndex = list.size() - 1;
        showDetail();
    }//GEN-LAST:event_lblLastMouseClicked

    private void pnlNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNewMouseClicked
        resetForm();
    }//GEN-LAST:event_pnlNewMouseClicked

    private void pnlSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSaveMouseClicked
        currentIndex = tblStudents.getSelectedRow();
        if (currentIndex == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sinh viên muốn lưu/sửa đổi điểm");
        } else {
            updateStudentGrade();
        }
    }//GEN-LAST:event_pnlSaveMouseClicked

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        currentIndex = tblStudents.getSelectedRow();
        showDetail();
    }//GEN-LAST:event_tblStudentsMouseClicked

    private void pnlLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogOutMouseClicked
        int confirmation = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất?",
                "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            this.dispose();
            EventQueue.invokeLater(() -> {
                new FrameDragListener(new LoginForm());
            });
        }
    }//GEN-LAST:event_pnlLogOutMouseClicked

    private void pnlDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDeleteMouseClicked
        currentIndex = tblStudents.getSelectedRow();
        if (currentIndex == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sinh viên muốn xoá điểm", "Thông báo lỗi",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            String maSV = list.get(currentIndex).getMaSV();
            String thongBao = "Bạn có chắc chắn muốn xoá điểm của sinh viên có mã " + maSV;
            int confirmation = JOptionPane.showConfirmDialog(this, thongBao,
                    "Thông báo xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirmation == JOptionPane.YES_OPTION) {
                if (StudentGradeDAO.delete(maSV) > 0) {
                    fillToTable();
                    resetForm();
                    JOptionPane.showMessageDialog(this, "Đã xoá điểm của" + maSV);
                } else {
                    JOptionPane.showMessageDialog(this, "Xoá thất bại", "Thông báo lỗi", 0);
                }
            }
        }
    }//GEN-LAST:event_pnlDeleteMouseClicked

    private void pnlEditModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditModeMouseClicked
        editModeState = !editModeState;
        editMode(editModeState);
    }//GEN-LAST:event_pnlEditModeMouseClicked

    private void lblAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAuthorMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://www.facebook.com/tai.nguyen.5832343/"));
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblAuthorMouseClicked

    private void lblAuthorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAuthorMouseEntered
        JLabel tempLabel = (JLabel) evt.getSource();
        tempLabel.setForeground(new Color(242, 113, 37));
    }//GEN-LAST:event_lblAuthorMouseEntered

    private void lblAuthorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAuthorMouseExited
        JLabel tempLabel = (JLabel) evt.getSource();
        tempLabel.setForeground(new Color(0, 102, 178));
    }//GEN-LAST:event_lblAuthorMouseExited

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (txtMaSVTim.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập mã sinh viên cần tìm");
            return;
        }

        for (Student x : list) {
            if (x.getMaSV().equals(txtMaSVTim.getText().toUpperCase())) {
                currentIndex = list.indexOf(x);
                showDetail();
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Không tồn tại mã sinh viên này");
    }//GEN-LAST:event_btnSearchActionPerformed

// Main was here :(

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner;
    private javax.swing.JLabel FormIcon;
    private javax.swing.JPanel MainContainer;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel fploy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblDiemTB;
    private javax.swing.JLabel lblEditState;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblLast;
    private javax.swing.JLabel lblMaSV;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblPrevious;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlDelete;
    private javax.swing.JPanel pnlEditMode;
    private javax.swing.JPanel pnlLogOut;
    private javax.swing.JPanel pnlNew;
    private javax.swing.JPanel pnlSave;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtGiaoDucTC;
    private javax.swing.JTextField txtMaSVTim;
    private javax.swing.JTextField txtTiengAnh;
    private javax.swing.JTextField txtTinHoc;
    // End of variables declaration//GEN-END:variables

    private void editMode(boolean state) {
        lblEditState.setText("Edit: " + (state ? "ON" : "OFF"));

        txtTiengAnh.setEditable(state);
        txtTinHoc.setEditable(state);
        txtGiaoDucTC.setEditable(state);
    }

    private void resetForm() {
        resetColorForFields();

        txtMaSVTim.setText("");
        lblHoTen.setText("");
        lblMaSV.setText("");
        txtTiengAnh.setText("");
        txtTinHoc.setText("");
        txtGiaoDucTC.setText("");
        lblDiemTB.setText("");

        tblStudents.clearSelection();
        currentIndex = tblStudents.getSelectedRow();
        editModeState = true;
        editMode(editModeState);
    }

    private void resetColorForFields() {
        txtTiengAnh.setBackground(Color.white);
        txtTinHoc.setBackground(Color.white);
        txtGiaoDucTC.setBackground(Color.white);
    }

    private void showDetail() {
        editModeState = false;
        editMode(editModeState);
        resetColorForFields();
        tblStudents.setRowSelectionInterval(currentIndex, currentIndex);

        Student temp = list.get(currentIndex);
        lblHoTen.setText(temp.getHoTen());
        lblMaSV.setText(temp.getMaSV());
        txtTiengAnh.setText(temp.getTiengAnh() + "");
        txtTinHoc.setText(temp.getTinHoc() + "");
        txtGiaoDucTC.setText(temp.getGDTC() + "");
        lblDiemTB.setText(temp.getDTB() + "");
    }

    private boolean checkForm() {
        StringBuilder sb = new StringBuilder();

        checkGradeField(sb, txtTiengAnh, txtTinHoc, txtGiaoDucTC);

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb, "Thông báo lỗi", 0);
            return false;
        }

        return true;
    }

    private void checkGradeField(StringBuilder sb, JTextField... fields) {
        Color errColor = new Color(236, 100, 75);
        for (JTextField txt : fields) {
            try {
                float grade = Float.parseFloat(txt.getText());
                if (grade > 10 || grade < 0) {
                    sb.append("Điểm phải lớn hơn 0 và nhỏ hơn 10");
                    txt.setBackground(errColor);
                    return;
                }
            } catch (Exception e) {
                sb.append("Điểm phải là số");
                txt.setBackground(errColor);
                return;
            }

            txt.setBackground(new Color(38, 194, 129));
        }
    }

    private Student getStudentFromFormInput() {
        Student student = new Student();
        student.setMaSV(lblMaSV.getText());
        student.setHoTen(lblHoTen.getText());
        student.setTiengAnh(Float.parseFloat(txtTiengAnh.getText()));
        student.setTinHoc(Float.parseFloat(txtTinHoc.getText()));
        student.setGDTC(Float.parseFloat(txtGiaoDucTC.getText()));
        return student;
    }

    private void updateStudentGrade() {
        if (!checkForm()) {
            return;
        }

        Student tempStudent = getStudentFromFormInput();
        if (StudentGradeDAO.save(tempStudent) > 0) {
            fillToTable();
            resetForm();
            JOptionPane.showMessageDialog(this, "Đã cập nhật thông tin thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thất bại");
        }
    }
}
