/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.StudentInforDAO;
import Helper.ImageHelper;
import Helper.Validator;
import Helper.FrameDragListener;
import Model.Student;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.EventQueue;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dev-StOrM
 */
public class StudentManagementForm extends javax.swing.JFrame {

    private ArrayList<Student> list;
    private int currentIndex = -1;
    private boolean editModeState;
    private final Color approvedColor = new Color(38, 194, 129);
    private final Color errorColor = new Color(236, 100, 75);

    /**
     * Creates new form StudentManagementForm
     *
     * @param username
     */
    public StudentManagementForm(String username) {
        initComponents();
        initTable();

        resetForm();
        fillToTable();

        lblUsername.setText(username);

        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }

    private void initTable() {
        DefaultTableModel tblModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        String columns[] = {"Mã SV", "Họ tên", "Email", "Số ĐT", "Giới tính", "Địa chỉ"};
        tblModel.setColumnIdentifiers(columns);

        tblStudents.setModel(tblModel);
        tblStudents.setSelectionMode(0);
        if (tblStudents.getColumnModel().getColumnCount() > 0) {
            tblStudents.getColumnModel().getColumn(0).setMaxWidth(60);
            tblStudents.getColumnModel().getColumn(1).setMinWidth(120);
            tblStudents.getColumnModel().getColumn(2).setMinWidth(120);
            tblStudents.getColumnModel().getColumn(3).setMinWidth(70);
            tblStudents.getColumnModel().getColumn(4).setMaxWidth(60);
            tblStudents.getColumnModel().getColumn(5).setMinWidth(120);
        }
    }

    private void fillToTable() {
        list = StudentInforDAO.getAll();
        DefaultTableModel tblModel = (DefaultTableModel) tblStudents.getModel();
        tblModel.setRowCount(0);
        for (Student x : list) {
            Object[] row = {x.getMaSV(), x.getHoTen(), x.getEmail(), x.getSoDT(),
                x.getGioiTinh() ? "Nam" : "Nữ", x.getDiaChi(), x.getHinh()};
            tblModel.addRow(row);
        }
        tblStudents.setModel(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngGender = new javax.swing.ButtonGroup();
        MainContainer = new javax.swing.JPanel();
        lblFormTitle = new javax.swing.JLabel();
        FormIcon = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        Banner = new javax.swing.JPanel();
        fploy = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JPanel();
        JLabel33 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSoDT = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        PanelImage = new javax.swing.JPanel();
        lblStudentImage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDiaChi = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnMinimize = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlNew = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlSave = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlDelete = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlEditMode = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblEditState = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblFirst = new javax.swing.JLabel();
        lblPrevious = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblLast = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        lblAuthor1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");
        setUndecorated(true);

        MainContainer.setBackground(java.awt.Color.white);
        MainContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        MainContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFormTitle.setText("Quản lý sinh viên");
        MainContainer.add(lblFormTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 140, 30));

        FormIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fpt_icon_1.png"))); // NOI18N
        MainContainer.add(FormIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 30));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_close_window_24px.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        MainContainer.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 30, 30));

        Banner.setBackground(new java.awt.Color(242, 111, 33));
        Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fploy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banner_crop.png"))); // NOI18N
        Banner.add(fploy, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, -1, 60));

        lblLogOut.setBackground(new java.awt.Color(242, 111, 33));
        lblLogOut.setToolTipText("Đăng xuất");
        lblLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogOutpnlNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogOutpnlNewMouseExited(evt);
            }
        });

        JLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Log-Out-icon.png"))); // NOI18N
        lblLogOut.add(JLabel33);

        Banner.add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 60, 60));

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername.setText("Username");
        lblUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Banner.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 180, 40));

        MainContainer.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 830, 60));

        jPanel3.setBackground(new java.awt.Color(248, 224, 219));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 119, 26)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Họ tên");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 54, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mã SV");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 12, -1, 30));

        txtMaSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaSV.setText("SV001");
        txtMaSV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txaDiaChiFocusGained(evt);
            }
        });
        jPanel3.add(txtMaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 13, 300, 30));

        txtHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHoTen.setText("Nguyen Van Teo");
        txtHoTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txaDiaChiFocusGained(evt);
            }
        });
        jPanel3.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 55, 300, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Email");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 96, -1, 30));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setText("teonv@gmail.com");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txaDiaChiFocusGained(evt);
            }
        });
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 97, 300, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Số ĐT");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 138, -1, 30));

        txtSoDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoDT.setText("0902993991");
        txtSoDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txaDiaChiFocusGained(evt);
            }
        });
        jPanel3.add(txtSoDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 139, 300, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Giới tính");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 180, -1, 30));

        btngGender.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");
        rdoNam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoNam.setOpaque(false);
        jPanel3.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 183, -1, -1));

        btngGender.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoNu.setText("Nữ");
        rdoNu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoNu.setOpaque(false);
        jPanel3.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 183, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Địa chỉ");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 221, 48, 30));

        PanelImage.setBackground(new java.awt.Color(248, 224, 219));
        PanelImage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        PanelImage.setPreferredSize(new java.awt.Dimension(165, 210));

        lblStudentImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentImage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblStudentImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblStudentImage.setMinimumSize(new java.awt.Dimension(150, 200));
        lblStudentImage.setPreferredSize(new java.awt.Dimension(150, 200));
        lblStudentImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStudentImageMouseClicked(evt);
            }
        });
        PanelImage.add(lblStudentImage);

        jPanel3.add(PanelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 165, 220));

        txaDiaChi.setColumns(20);
        txaDiaChi.setRows(5);
        txaDiaChi.setText("Lâm đồng");
        txaDiaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txaDiaChiFocusGained(evt);
            }
        });
        jScrollPane3.setViewportView(txaDiaChi);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 300, -1));

        MainContainer.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 620, 340));

        tblStudents.setBackground(new java.awt.Color(248, 224, 219));
        tblStudents.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblStudents.setForeground(new java.awt.Color(51, 51, 51));
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ Tên", "Email", "Số ĐT", "Giới tính", "Địa chỉ"
            }
        ));
        tblStudents.setFocusable(false);
        tblStudents.setShowGrid(false);
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);
        if (tblStudents.getColumnModel().getColumnCount() > 0) {
            tblStudents.getColumnModel().getColumn(0).setMaxWidth(60);
            tblStudents.getColumnModel().getColumn(1).setMinWidth(120);
            tblStudents.getColumnModel().getColumn(2).setMinWidth(120);
            tblStudents.getColumnModel().getColumn(3).setMinWidth(70);
            tblStudents.getColumnModel().getColumn(4).setMaxWidth(60);
            tblStudents.getColumnModel().getColumn(5).setMinWidth(120);
        }

        MainContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 830, 180));

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_minimize_window_24px_1.png"))); // NOI18N
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        MainContainer.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 30, 30));

        jPanel4.setBackground(new java.awt.Color(242, 111, 33));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setFocusable(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(13, 176, 75));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, -1));

        pnlNew.setBackground(new java.awt.Color(242, 111, 33));
        pnlNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNewMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-32px.png"))); // NOI18N

        jLabel16.setDisplayedMnemonic('N');
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("New");

        jSeparator2.setForeground(new java.awt.Color(13, 176, 75));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout pnlNewLayout = new javax.swing.GroupLayout(pnlNew);
        pnlNew.setLayout(pnlNewLayout);
        pnlNewLayout.setHorizontalGroup(
            pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNewLayout.setVerticalGroup(
            pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlNewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );

        jPanel4.add(pnlNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 50));

        pnlSave.setBackground(new java.awt.Color(242, 111, 33));
        pnlSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSavepnlNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSavepnlNewMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save-32px.png"))); // NOI18N

        jLabel11.setDisplayedMnemonic('S');
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Save");

        javax.swing.GroupLayout pnlSaveLayout = new javax.swing.GroupLayout(pnlSave);
        pnlSave.setLayout(pnlSaveLayout);
        pnlSaveLayout.setHorizontalGroup(
            pnlSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaveLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSaveLayout.setVerticalGroup(
            pnlSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSaveLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(pnlSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 50));

        pnlDelete.setBackground(new java.awt.Color(242, 111, 33));
        pnlDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDeletepnlNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDeletepnlNewMouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete-32px.png"))); // NOI18N

        jLabel13.setDisplayedMnemonic('D');
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Delete");

        javax.swing.GroupLayout pnlDeleteLayout = new javax.swing.GroupLayout(pnlDelete);
        pnlDelete.setLayout(pnlDeleteLayout);
        pnlDeleteLayout.setHorizontalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlDeleteLayout.setVerticalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(pnlDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));

        pnlEditMode.setBackground(new java.awt.Color(242, 111, 33));
        pnlEditMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEditMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEditModeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlEditModepnlNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlEditModepnlNewMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update-32px.png"))); // NOI18N

        lblEditState.setDisplayedMnemonic('U');
        lblEditState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEditState.setForeground(new java.awt.Color(255, 255, 255));
        lblEditState.setText("Edit: ");

        javax.swing.GroupLayout pnlEditModeLayout = new javax.swing.GroupLayout(pnlEditMode);
        pnlEditMode.setLayout(pnlEditModeLayout);
        pnlEditModeLayout.setHorizontalGroup(
            pnlEditModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditModeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblEditState, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlEditModeLayout.setVerticalGroup(
            pnlEditModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditModeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditModeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addComponent(lblEditState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(pnlEditMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 50));

        jSeparator4.setForeground(new java.awt.Color(13, 176, 75));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, -1));

        lblFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/first-32px.png"))); // NOI18N
        lblFirst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFirstMouseClicked(evt);
            }
        });
        jPanel4.add(lblFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        lblPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/previous-32px.png"))); // NOI18N
        lblPrevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPreviousMouseClicked(evt);
            }
        });
        jPanel4.add(lblPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/next-32px.png"))); // NOI18N
        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });
        jPanel4.add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        lblLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/last-32px.png"))); // NOI18N
        lblLast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLastMouseClicked(evt);
            }
        });
        jPanel4.add(lblLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(13, 176, 75));
        jSeparator5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jSeparator5.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 10));

        MainContainer.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 350));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 2);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        lblAuthor1.setForeground(new java.awt.Color(0, 102, 204));
        lblAuthor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthor1.setText("© Copyright - Nguyễn Trọng Tài - PS15069");
        lblAuthor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAuthor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAuthor1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAuthor1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAuthor1MouseExited(evt);
            }
        });
        jPanel2.add(lblAuthor1);

        MainContainer.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 830, 20));

        getContentPane().add(MainContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        int confirmation = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?",
                "Thoát chương trình", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        setState(GradeManagementForm.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void pnlNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNewMouseEntered
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(255, 137, 91));
    }//GEN-LAST:event_pnlNewMouseEntered

    private void pnlNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNewMouseExited
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(242, 111, 33));
    }//GEN-LAST:event_pnlNewMouseExited

    private void pnlSavepnlNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSavepnlNewMouseEntered
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(255, 137, 91));
    }//GEN-LAST:event_pnlSavepnlNewMouseEntered

    private void pnlSavepnlNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSavepnlNewMouseExited
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(242, 111, 33));
    }//GEN-LAST:event_pnlSavepnlNewMouseExited

    private void pnlDeletepnlNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDeletepnlNewMouseEntered
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(255, 137, 91));
    }//GEN-LAST:event_pnlDeletepnlNewMouseEntered

    private void pnlDeletepnlNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDeletepnlNewMouseExited
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(242, 111, 33));
    }//GEN-LAST:event_pnlDeletepnlNewMouseExited

    private void pnlEditModepnlNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditModepnlNewMouseEntered
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(255, 137, 91));
    }//GEN-LAST:event_pnlEditModepnlNewMouseEntered

    private void pnlEditModepnlNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditModepnlNewMouseExited
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(242, 111, 33));
    }//GEN-LAST:event_pnlEditModepnlNewMouseExited

    private void pnlNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNewMouseClicked
        resetForm();
    }//GEN-LAST:event_pnlNewMouseClicked

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        currentIndex = tblStudents.getSelectedRow();
        showDetail();
    }//GEN-LAST:event_tblStudentsMouseClicked

    private void lblFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFirstMouseClicked
        currentIndex = 0;
        showDetail();
    }//GEN-LAST:event_lblFirstMouseClicked

    private void lblPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPreviousMouseClicked
        currentIndex--;
        if (currentIndex < 0) {
            currentIndex = list.size() - 1;
        }
        showDetail();
    }//GEN-LAST:event_lblPreviousMouseClicked

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        currentIndex++;
        if (currentIndex >= list.size()) {
            currentIndex = 0;
        }
        showDetail();
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLastMouseClicked
        currentIndex = list.size() - 1;
        showDetail();
    }//GEN-LAST:event_lblLastMouseClicked

    private void pnlSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSaveMouseClicked
        currentIndex = tblStudents.getSelectedRow();
        if (currentIndex == -1) {
            insertNewStudent();
        } else {
            updateStudentInfo();
        }
    }//GEN-LAST:event_pnlSaveMouseClicked

    private void lblAuthor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAuthor1MouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://www.facebook.com/tai.nguyen.5832343/"));
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblAuthor1MouseClicked

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        int confirmation = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất?",
                "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            this.dispose();
            EventQueue.invokeLater(() -> {
                new FrameDragListener(new LoginForm());
            });
        }
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void lblLogOutpnlNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutpnlNewMouseEntered
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(255, 137, 91));
    }//GEN-LAST:event_lblLogOutpnlNewMouseEntered

    private void lblLogOutpnlNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutpnlNewMouseExited
        JPanel activatedPanel = (JPanel) evt.getSource();
        activatedPanel.setBackground(new Color(242, 111, 33));
    }//GEN-LAST:event_lblLogOutpnlNewMouseExited

    private void lblAuthor1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAuthor1MouseEntered
        JLabel tempLabel = (JLabel) evt.getSource();
        tempLabel.setForeground(new Color(242, 113, 37));
    }//GEN-LAST:event_lblAuthor1MouseEntered

    private void lblAuthor1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAuthor1MouseExited
        JLabel tempLabel = (JLabel) evt.getSource();
        tempLabel.setForeground(new Color(0, 102, 178));
    }//GEN-LAST:event_lblAuthor1MouseExited

    private void pnlDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDeleteMouseClicked
        currentIndex = tblStudents.getSelectedRow();
        if (currentIndex == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sinh viên muốn xoá", "Thông báo lỗi",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            String maSV = list.get(currentIndex).getMaSV();
            String thongBao = "Bạn có chắc chắn muốn xoá sinh viên có mã " + maSV;
            int confirmation = JOptionPane.showConfirmDialog(this, thongBao,
                    "Thông báo xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirmation == JOptionPane.YES_OPTION) {
                if (StudentInforDAO.delete(maSV) > 0) {
//                    // delete file in project too
//                    try {
//                        Files.delete(Paths.get("src\\Images\\" + imageToDelete));
//                    } catch (Exception ex) {
//                        System.out.println(ex.toString());
//                    }

                    // update list, table
                    fillToTable();
                    resetForm();

                    JOptionPane.showMessageDialog(this, "Đã xoá " + maSV);
                } else {
                    JOptionPane.showMessageDialog(this, "Xoá thất bại", "Thông báo lỗi", 0);
                }
            }
        }
    }//GEN-LAST:event_pnlDeleteMouseClicked

    private void pnlEditModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditModeMouseClicked
        editModeState = !editModeState;
        editMode(editModeState);
    }//GEN-LAST:event_pnlEditModeMouseClicked

    private void txaDiaChiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txaDiaChiFocusGained
        try {
            JTextField txt = (JTextField) evt.getSource();
            txt.setBackground(Color.white);
        } catch (Exception e) {
            txaDiaChi.setBackground(Color.white);
        }
    }//GEN-LAST:event_txaDiaChiFocusGained

    private void lblStudentImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStudentImageMouseClicked
        // if editMode is in OFF-state, user can't edit Image
        if (editModeState == false) {
            return;
        }

        JFileChooser chooser = new JFileChooser("src\\Images");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg", "jpeg", "png");
        chooser.setFileFilter(filter);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                String tempImagePath = chooser.getSelectedFile().getAbsolutePath();
                lblStudentImage.setIcon(ImageHelper.resize(lblStudentImage, tempImagePath));
                lblStudentImage.setText(null);
            } catch (IOException ex) {
                System.out.println(ex.toString());
            }
        }
    }//GEN-LAST:event_lblStudentImageMouseClicked

// Main was here :(
    public static void main(String[] args) {
        EventQueue.invokeLater(() -> {
            new FrameDragListener(new StudentManagementForm("huhu"));
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner;
    private javax.swing.JLabel FormIcon;
    private javax.swing.JLabel JLabel33;
    private javax.swing.JPanel MainContainer;
    private javax.swing.JPanel PanelImage;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.ButtonGroup btngGender;
    private javax.swing.JLabel fploy;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblAuthor1;
    private javax.swing.JLabel lblEditState;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JLabel lblLast;
    private javax.swing.JPanel lblLogOut;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblPrevious;
    private javax.swing.JLabel lblStudentImage;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlDelete;
    private javax.swing.JPanel pnlEditMode;
    private javax.swing.JPanel pnlNew;
    private javax.swing.JPanel pnlSave;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextArea txaDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtSoDT;
    // End of variables declaration//GEN-END:variables

    private void editMode(boolean state) {
        lblEditState.setText("Edit: " + (state ? "ON" : "OFF"));

        // if currentIndex == -1 : It means program is executing insert new student's information process
        // else : It means program is executing update student's information process -> Can't edit MaSV field
        if (currentIndex == -1 && state) {
            txtMaSV.setEditable(true);
        } else {
            txtMaSV.setEditable(false);
        }

        txtHoTen.setEditable(state);
        txtEmail.setEditable(state);
        txtSoDT.setEditable(state);
        txaDiaChi.setEditable(state);
        
        if (currentIndex == -1) {
            rdoNam.setEnabled(state);
            rdoNu.setEnabled(state);
        } else if (tblStudents.getValueAt(currentIndex, 4) == "Nam") {
            rdoNu.setEnabled(false);
            rdoNam.setEnabled(true);
        } else {
            rdoNu.setEnabled(true);
            rdoNam.setEnabled(false);
        }
    }

    private void resetForm() {
        txtMaSV.setText("");
        txtHoTen.setText("");
        txtEmail.setText("");
        txtSoDT.setText("");
        rdoNam.setSelected(true);
        txaDiaChi.setText("");

        tblStudents.clearSelection();
        currentIndex = tblStudents.getSelectedRow();
        editModeState = true;
        editMode(editModeState);

        lblStudentImage.setIcon(null);
        lblStudentImage.setText("Chưa chọn hình");
        resetColorForFields();
    }

    private void resetColorForFields() {
        txtMaSV.setBackground(Color.white);
        txtHoTen.setBackground(Color.white);
        txtEmail.setBackground(Color.white);
        txtSoDT.setBackground(Color.white);
        txaDiaChi.setBackground(Color.white);
    }

    private void showDetail() {
        editModeState = false;
        editMode(editModeState);
        resetColorForFields();
        tblStudents.setRowSelectionInterval(currentIndex, currentIndex);

        Student temp = list.get(currentIndex);
        txtMaSV.setText(temp.getMaSV());
        txtHoTen.setText(temp.getHoTen());
        txtEmail.setText(temp.getEmail());
        txtSoDT.setText(temp.getSoDT());
        if (temp.getGioiTinh()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        txaDiaChi.setText(temp.getDiaChi());
        // assign image's file path to tempImagePath, prepare for copy or update process
//        tempImagePath = "src/Images/" + temp.getHinh();
//        lblStudentImage.setIcon(ResizeImage.qualityResize(tempImagePath));

        try {
            ImageIcon icon = ImageHelper.revertFromArrayByte(temp.getHinh());
            lblStudentImage.setText(null);
            lblStudentImage.setIcon(icon);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi tải hình", "Thông báo lỗi", 0);
        }
    }

    private Student getStudentFromFormInput() {
        Student student = new Student();
        student.setMaSV(txtMaSV.getText().trim());
        student.setHoTen(txtHoTen.getText().trim());
        student.setEmail(txtEmail.getText().trim());
        student.setSoDT(txtSoDT.getText().trim());
        student.setGioiTinh(rdoNam.isSelected());
        student.setDiaChi(txaDiaChi.getText().trim());
        try {
            student.setHinh(ImageHelper.convertToByteArray(lblStudentImage.getIcon()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Thông báo lỗi", 0);
            return null;
        }
        return student;
    }

    private boolean checkForm() {
        StringBuilder sb = new StringBuilder();

        // txtMaSV
        if (!Validator.isValidMaSV(txtMaSV.getText())) {
            txtMaSV.setBackground(errorColor);
            sb.append("Nhập mã Sinh viên với định dạng: \"SVxxx\","
                    + " với x là một số bất kỳ (Ví dụ: SV001, SV002...)\n");
        } else {
            txtMaSV.setBackground(approvedColor);
        }

        // txtHoTen
        if (Validator.isValidName(txtHoTen.getText())) {
            txtHoTen.setBackground(approvedColor);
        } else {
            txtHoTen.setBackground(errorColor);
            sb.append("Nhập chính xác Họ Tên\n");
        }

        // txtEmail
        if (Validator.isValidEmail(txtEmail.getText())) {
            txtEmail.setBackground(approvedColor);
        } else {
            txtEmail.setBackground(errorColor);
            sb.append("Nhập chính xác Email\n");
        }

        // txtSoDT
        if (Validator.isValidPhoneNumber(txtSoDT.getText())) {
            txtSoDT.setBackground(approvedColor);
        } else {
            txtSoDT.setBackground(errorColor);
            sb.append("Nhập chính xác Số điện thoại\n");
        }

        // txaDiaChi
        if (txaDiaChi.getText().trim().equals("")) {
            txaDiaChi.setBackground(errorColor);
            sb.append("Nhập địa chỉ\n");
        } else {
            txaDiaChi.setBackground(approvedColor);
        }

        // lblStudentImage
        if (lblStudentImage.getIcon() == null) {
            sb.append("Hãy chọn hình đại diện\n");
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb, "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    private boolean isDuplicateMaSV(String maSV) {
        if (StudentInforDAO.get(maSV) != null) {
            String errMsg = "Đã tồn tại Mã sinh viên này, chọn mã khác\n";
            JOptionPane.showMessageDialog(this, errMsg, "Thông báo lỗi", 0);
        }
        return false;
    }

    // Inputs must be valid and MaSV must not be duplicated
    private void insertNewStudent() {
        if (!checkForm()) {
            return;
        }

        String maSV = txtMaSV.getText().trim();
        if (isDuplicateMaSV(maSV)) {
            return;
        }

        Student tempStudent = getStudentFromFormInput();
        if (tempStudent == null) {
            return;
        }

        // save to database and update list, table
        if (StudentInforDAO.save(tempStudent) > 0) {
            fillToTable();
            resetForm();
            JOptionPane.showMessageDialog(this, "Đã thêm sinh viên thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm sinh viên thất bại");
        }
    }

    private void updateStudentInfo() {
        if (!checkForm()) {
            return;
        }

        Student tempStudent = getStudentFromFormInput();
        if (tempStudent == null) {
            return;
        }

        // save to database and update list, table
        if (StudentInforDAO.update(tempStudent) > 0) {
            fillToTable();
            resetForm();
            JOptionPane.showMessageDialog(this, "Đã cập nhật thông tin thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thất bại");
        }
    }

    // rename and copy and image to src project
//    private byte[] copyImageToSource(String maSV) {
//        String extension = tempImagePath.substring(tempImagePath.lastIndexOf('.') + 1);
//        String newFileImageName = maSV + "." + extension;
//        try {
//            Files.copy(Paths.get(tempImagePath), Paths.get("src\\Images\\" + newFileImageName),
//                    StandardCopyOption.REPLACE_EXISTING);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage(),
//                    "Lỗi copy hình vào source", JOptionPane.ERROR_MESSAGE);
//        }
//        return newFileImageName;        
//    }
}
